import { useState, useEffect } from 'react'
import { getModels, estimateCost } from '../services/api'
import { BarChart, Bar, XAxis, YAxis, CartesianGrid, Tooltip, ResponsiveContainer } from 'recharts'

function CostCalculator() {
  const [models, setModels] = useState([])
  const [selectedModels, setSelectedModels] = useState([])
  const [inputTokens, setInputTokens] = useState(10)
  const [outputTokens, setOutputTokens] = useState(5)
  const [estimates, setEstimates] = useState([])
  const [loading, setLoading] = useState(false)

  useEffect(() => {
    getModels().then(data => {
      const chatModels = (data.models || []).filter(m => m.category === 'chat' || m.category === 'embedding')
      setModels(chatModels)
      setSelectedModels(chatModels.slice(0, 4).map(m => m.id))
    }).catch(console.error)
  }, [])

  const handleCalculate = async () => {
    setLoading(true)
    try {
      const results = await Promise.all(
        selectedModels.map(id => estimateCost(id, inputTokens, outputTokens))
      )
      setEstimates(results)
    } catch (err) {
      console.error('Cost estimation failed:', err)
    } finally {
      setLoading(false)
    }
  }

  const toggleModel = (modelId) => {
    setSelectedModels(prev =>
      prev.includes(modelId)
        ? prev.filter(id => id !== modelId)
        : prev.length < 6 ? [...prev, modelId] : prev
    )
  }

  const chartData = estimates.map(e => ({
    name: e.model_name.length > 14 ? e.model_name.slice(0, 14) + '...' : e.model_name,
    'Monthly Cost': e.total_monthly_cost,
  }))

  return (
    <div className="cost-calculator">
      {/* Input Section */}
      <div className="cost-input-section">
        <h2 className="card-title">Usage Parameters</h2>

        <div className="form-group">
          <label>Monthly Input Tokens (millions)</label>
          <input
            type="number"
            min="0.1"
            step="0.5"
            value={inputTokens}
            onChange={e => setInputTokens(parseFloat(e.target.value) || 0)}
          />
          <div className="helper-text">Tokens sent to the model per month</div>
        </div>

        <div className="form-group">
          <label>Monthly Output Tokens (millions)</label>
          <input
            type="number"
            min="0.1"
            step="0.5"
            value={outputTokens}
            onChange={e => setOutputTokens(parseFloat(e.target.value) || 0)}
          />
          <div className="helper-text">Tokens generated by the model per month</div>
        </div>

        <div className="form-group">
          <label>Select Models to Compare (up to 6)</label>
          <div className="multi-select" style={{ maxHeight: 200, overflowY: 'auto' }}>
            {models.map(m => (
              <span
                key={m.id}
                className={`chip ${selectedModels.includes(m.id) ? 'selected' : ''}`}
                onClick={() => toggleModel(m.id)}
              >
                {m.name}
              </span>
            ))}
          </div>
          <div className="helper-text">{selectedModels.length} model(s) selected</div>
        </div>

        <button
          className="btn btn-primary"
          onClick={handleCalculate}
          disabled={selectedModels.length === 0 || loading}
        >
          {loading ? 'Calculating...' : 'Calculate Costs'}
        </button>
      </div>

      {/* Results Section */}
      <div className="cost-result-section">
        <h2 className="card-title">Cost Estimates</h2>

        {estimates.length === 0 ? (
          <div style={{ textAlign: 'center', padding: 40, color: 'var(--text-secondary)' }}>
            <p>Configure usage parameters and click "Calculate Costs" to see estimates.</p>
          </div>
        ) : (
          <>
            {/* Cheapest option highlight */}
            {(() => {
              const cheapest = [...estimates].sort((a, b) => a.total_monthly_cost - b.total_monthly_cost)[0]
              return (
                <div className="cost-result-card">
                  <div style={{ fontSize: '0.75rem', color: 'var(--text-secondary)', marginBottom: 4 }}>
                    Most Cost-Effective
                  </div>
                  <div style={{ fontSize: '1rem', fontWeight: 700, marginBottom: 8 }}>{cheapest.model_name}</div>
                  <div className="cost-amount">${cheapest.total_monthly_cost.toLocaleString()}</div>
                  <div className="cost-period">per month</div>
                  <div style={{ fontSize: '0.75rem', color: 'var(--text-secondary)', marginTop: 8 }}>
                    ${cheapest.annual_cost.toLocaleString()} / year
                  </div>
                </div>
              )
            })()}

            {/* Chart */}
            <div style={{ marginBottom: 24 }}>
              <ResponsiveContainer width="100%" height={200}>
                <BarChart data={chartData} margin={{ top: 5, right: 5, left: 0, bottom: 5 }}>
                  <CartesianGrid strokeDasharray="3 3" stroke="#f0f0f0" />
                  <XAxis dataKey="name" tick={{ fontSize: 10 }} />
                  <YAxis tick={{ fontSize: 10 }} tickFormatter={v => `$${v}`} />
                  <Tooltip
                    contentStyle={{ borderRadius: 8, fontSize: 12 }}
                    formatter={(value) => [`$${value.toLocaleString()}`, 'Monthly Cost']}
                  />
                  <Bar dataKey="Monthly Cost" fill="#0078d4" radius={[4, 4, 0, 0]} />
                </BarChart>
              </ResponsiveContainer>
            </div>

            {/* Breakdown */}
            <div className="cost-breakdown">
              {[...estimates].sort((a, b) => a.total_monthly_cost - b.total_monthly_cost).map(est => (
                <div key={est.model_id} className="cost-row">
                  <div>
                    <div style={{ fontWeight: 600, fontSize: '0.85rem' }}>{est.model_name}</div>
                    <div style={{ fontSize: '0.7rem', color: 'var(--text-tertiary)' }}>
                      Input: ${est.monthly_input_cost} | Output: ${est.monthly_output_cost}
                    </div>
                  </div>
                  <div style={{ textAlign: 'right' }}>
                    <div style={{ fontWeight: 700, fontSize: '0.9rem' }}>${est.total_monthly_cost}/mo</div>
                    <div style={{ fontSize: '0.7rem', color: 'var(--text-tertiary)' }}>${est.annual_cost}/yr</div>
                  </div>
                </div>
              ))}
            </div>
          </>
        )}
      </div>
    </div>
  )
}

export default CostCalculator
